#MySql 셋팅
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_db
    username: root
    password: 1111
  sql:
    init:
      mode: never
      # always : 매번, embedded : 내장 DB만, never : 모든 동작 안함
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope: profile, email

          naver:
            client-id:
            client-secret:
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id:
            client-secret:
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post  # ✅ 꼭 필요
            scope:
              - profile_nickname
              - account_email

        provider:
          # spring에 google, instagram 등의 사이트 provider 기본적으로 내장되어있음
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

    logging:
      level:
        org.springframework.security: DEBUG
        com.my.jwt: DEBUG
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbbPLAINTEXT